

[versions]
accompanistPermissions = "0.36.0"
agp = "8.12.3"
androidxJunit = "1.1.5"
coilCompose = "2.7.0"
kotlin = "2.2.20"
# accompanistPager is deprecated, use androidx.compose.foundation.pager instead
# accompanistPager = "<latest_version>" # REMOVE THIS
accompanistPermissionsVersion = "0.34.0" # This is kept but be aware it's from an older library set
activityCompose = "1.11.0"
coreKtx = "1.12.0"
foundationPager = "1.6.0" # Corresponds to foundation 1.6.x, let's align
foundation = "1.6.7" # Align with other compose libraries
coreTesting = "2.2.0"
converterGson = "3.0.0"
koinAndroid = "4.1.1"
koinAndroidxCompose = "4.1.1"
koinTest = "4.1.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxCoroutines = "1.10.2" # Use a single version for all coroutines libraries
lifecycleRuntimeKtx = "2.9.3"
lifecycleViewmodelKtx = "2.9.4"
composeBom = "2024.09.00"
materialIconsExtended = "1.6.7" # Align with other compose libraries
mockk = "1.13.5"
navigationCompose = "2.9.5"
robolectricVersion = "4.12.2"
uiTextGoogleFonts = "1.6.7" # Align with other compose libraries
runtime = "1.6.7" # Align with other compose libraries
adsMobileSdk = "0.20.0-beta01"
uiText = "1.6.7" # Align with other compose libraries
loggingInterceptor = "5.1.0"
okhttp = "5.1.0"
playServicesLocation = "21.3.0"
retrofit = "3.0.0"
mapsCompose = "2.11.4"
places = "5.0.0"
playServicesMaps = "18.1.0"
runtimeLivedata = "1.6.7"
foundationLayoutVersion = "1.9.3"
animation = "1.9.4" # Align with other compose libraries


[libraries]
# REMOVED accompanist-pager as it is deprecated
# accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }


accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissionsVersion" }
accompanist-permissions-v0360 = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-compose-foundation-pager = { module = "androidx.compose.foundation:foundation-pager", version.ref = "foundationPager" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
robolectric-v4122 = { module = "org.robolectric:robolectric", version.ref = "robolectricVersion" }
androidx-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
ads-mobile-sdk = { group = "com.google.android.libraries.ads.mobile.sdk", name = "ads-mobile-sdk", version.ref = "adsMobileSdk" }
androidx-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koinTest" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutines" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
places = { module = "com.google.android.libraries.places:places", version.ref = "places" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayoutVersion" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "animation" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

